### ISSUE TITLE
建议使用OneDrive之类的云存储而不是GitHub储存库储存图形

### ISSUE THREAD

**Issue by Muska-Ami** [Natsusomekeishi/ImgURL#1]
GH就5G，存不了多少东西 而且我看你这个好像是vercel，vercel请求太多大文件好像会404，建议部署OneManager/onedrive-vercel-index来调用云存储文件
比如我OD是E5开发者单个账户可以获得最多5T的储存

**Comment by Natsusomekeishi** [comment]
没事，其实就是放着玩的（
实际上我会用我朋友提供给我的图床，非常的大，非常的稳定，非常的高效快速(*^▽^*)
